services:
  bot:
    container_name: mkitty-bot
    image: ghcr.io/black7spades/mkittybot:latest
    restart: unless-stopped
    ports:
      - "2013:2013"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rsshub

  rsshub:
    container_name: mkitty-rsshub
    build:
      context: .
      dockerfile: Dockerfile.rsshub
    image: mkitty-rsshub:latest
    restart: unless-stopped
    environment:
      - CACHE_TYPE=memory
    ports:
      - "1200:1200"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
