services:
  starrbot:
    container_name: starrbot
    image: ghcr.io/black7spades/starrbot:latest
    build: .
    restart: unless-stopped
    ports:
      - "2013:2013"
    volumes:
      - ./data:/app/data
