FROM diygod/rsshub:latest

USER root

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    glib \
    libstdc++ \
    dbus \
    ttf-freefont \
    font-noto-cjk \
  && npm install -g patchright \
  && patchright install --with-deps chromium
