services:
  bot:
    image: ghcr.io/black7spades/mkittybot:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - rsshub

  rsshub:
    image: diygod/rsshub
    restart: unless-stopped
    environment:
      - CACHE_TYPE=memory
    ports:
      - "1200:1200"
