FROM diygod/rsshub:latest

USER root

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    glib \
    libstdc++ \
    dbus \
    ttf-freefont \
    font-noto-cjk \
  && npm install -g playwright \
  && playwright install --with-deps chromium

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
  PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
